<?php

namespace CH\Skeleton\Tests;

use CH\Skeleton\Application;
use CH\Skeleton\PHPUnit\TestCase;

class ApplicationTest extends TestCase
{
    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testGetEnvironmentSet()
    {
        $app = new Application();
        $this->assertEquals(Application::ENV_LIVE, $app->getEnvironment());
        $this->assertEquals($app, $app->setEnvironment(Application::ENV_STAGE));
        $this->assertEquals(Application::ENV_STAGE, $app->getEnvironment());
    }

    public function testGetEnvironmentServerVar()
    {
        $app = new Application();
        $_SERVER['HTTP_HOST'] = 'localhost';
        $this->assertEquals(Application::ENV_LOCAL, $app->getEnvironment());
    }
}
